name: publish-docker

on:
  push:
    branches:

jobs:
  push-to-registry:
    name: push to Docker HUb
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker HUb
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Extract meta informantion
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: aminulhoque0/docker-github-action
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dokcerfile
          push: true

          tags: ${{ steps.meta.outputs.tags }}
