name: mocha test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: # Correct indentation
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run tests
        run: yarn test
      - run: echo "All test passed!"
